version: 2.1

jobs:
  extraction:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
  compilation:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "compilation code"
          command: |
            echo "compilation"
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "test du code"
          command: |
            echo "test du code"

  deploiement:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "deploiement image"
          command: |
            echo "deploiement"
            
workflows:
  checkout-test-workflow:
    jobs:
      - extraction
      - compilation:
          requires:
            - extraction
      - test:
          requires:
            - compilation
      - deploiement:
          requires:
            - test
           
