version: 2.1

jobs:
  extraction:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
  supervision_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout 
      
  compilation:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "compilation code"
          command: |
            echo "compilation"
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "test du code"
          command: |
            echo "test du code"

  deploiement_azur:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "deploiement azur"
          command: |
            echo "deploiement azur"

  deploiement_ibm:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "deploiement ibm"
          command: |
            echo "deploiement ibm"    
            
workflows:
  checkout-test-workflow:
    jobs:
      - extraction
      - supervision_code:
          requires:
            - extraction
      - compilation:
          requires:
            - extraction
      - test:
          requires:
            - compilation
      - deploiement_azur:
          requires:
            - test
      - deploiement_ibm:
          requires:
            - test
